allowBuilds:
  esbuild: false # https://github.com/evanw/esbuild/issues/4085#issuecomment-2696009329
  sharp: false # https://sharp.pixelplumbing.com/install/: "When using pnpm, add sharp to ignoredBuiltDependencies to silence warnings."
